drop database subconsultas;
create database subconsultas;
use subconsultas;

CREATE TABLE DEPARTAMENTO (
CODIGODEPARTAMENTO int NOT NULL,
NOME varchar(90) NOT NULL,
PRIMARY KEY (CODIGODEPARTAMENTO)); 

CREATE TABLE FUNCIONARIO (
CODIGOFUNCIONARIO int not null,
NOME varchar(90) not null,
CPF char(15),
SEXO char(1) NOT NULL,
DTNASCIMENTO date NOT NULL,
SALARIO real,
CODIGODEPARTAMENTO int,
PRIMARY KEY (CODIGOFUNCIONARIO));

ALTER TABLE FUNCIONARIO ADD FOREIGN KEY (CODIGODEPARTAMENTO) REFERENCES DEPARTAMENTO (CODIGODEPARTAMENTO);

INSERT INTO DEPARTAMENTO (CODIGODEPARTAMENTO, NOME) VALUES (1, 'Tecnologia da Informação');
INSERT INTO DEPARTAMENTO (CODIGODEPARTAMENTO, NOME) VALUES (2, 'Contabilidade');
INSERT INTO DEPARTAMENTO (CODIGODEPARTAMENTO, NOME) VALUES (3, 'Marketing');

INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO, CODIGODEPARTAMENTO) VALUES (1, 'ROBERTA SILVA BRASIL', NULL, 'F', '1980-02-20', 7000,1);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO, CODIGODEPARTAMENTO) VALUES (2, 'MARIA SILVA BRASIL', NULL, 'F', '1988-09-15', 9500,2);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO, CODIGODEPARTAMENTO) VALUES (3, 'GABRIELLA PEREIRA LIMA', NULL, 'F', '1990-02-25',6000,1);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO, CODIGODEPARTAMENTO) VALUES (4, 'MARCOS PEREIRA BRASIL', NULL, 'M', '1999-02-25', 6000,2);
INSERT INTO FUNCIONARIO (CODIGOFUNCIONARIO, NOME, CPF, SEXO, DTNASCIMENTO, SALARIO, CODIGODEPARTAMENTO) VALUES (5, 'HEMERSON SILVA BRASIL', NULL, 'M', '1992-12-20',4000, NULL);
